In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.9.0


In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [28]:
vector = torch.tensor([1, 2, 3])
vector

tensor([1, 2, 3])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 4, 3])

In [15]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [16]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2566, 0.8496, 0.8422, 0.0901],
        [0.3045, 0.3549, 0.8141, 0.7578],
        [0.0222, 0.8576, 0.7323, 0.5436]])

In [17]:
random_tensor.ndim

2

In [18]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [33]:
%%time
torch.matmul(vector, vector)

CPU times: user 132 μs, sys: 6 μs, total: 138 μs
Wall time: 144 μs


tensor(14)

In [41]:
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])

tensor_B = torch.tensor([[1, 2], [3, 4], [5, 6]])

In [44]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])